### ISSUE TITLE
Support stream multiplexing for websockets

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/js-ws#2]
### Specification

To avoid the overhead of creating and negotiation separate websocket connections per RPC call. We need to add the ability to multiplex streams over a single websocket stream.

Since webstreams are a message based protocal, we can wrap each message in a header to add data for multiplexing. Worst case we can searalized and deseralize JSON in a stream, the same way we do for the JSONRPC messages.

This will be abstracted on top of webstreams. We will have a multiplexing transform that will implement the multiplexing and a demux transform that does the reverse.

#### Message structure

A streamed websocket message is constructed in three parts:

```
+----------------------+----------------+------------------------+
|   QUIC-style Varint  |  Message Type  |       Payload          |
+----------------------+----------------+------------------------+
```

The QUIC-style Varint is used to represent the monotonic ID of the up to the limits of a 62 bit unsigned integer (stored as big-endian).

The message type is a byte that represents the type of the message received:

```ts
enum MessageType {
  DATA = 0x00,
  ACK = 0x01,
  ERROR = 0x02,
  CLOSE = 0x03,
}
```

##### `Variable-Length Integer Encoding`

This is to be done similar to QUIC.
The `Variable-Length Integer Encoding`, or VarInt is an unsigned integer represented by anywhere from 1 to 8 bytes. It should use the first two bits of the initial byte to determine how many bytes the VarInt uses. Hence the usable bits of an encoded VarInt is 2 bits smaller than that of a u8, u16, u32, u64 number.

| VarInt Prefix | Size (bytes) | Usable Bits |
| - | - | - |
| `0b00` | 1 | 6 |
| `0b01` | 2 | 14 |
| `0b10` | 4 | 30 |
| `0b11` | 8 | 62 |

As the maximum unsigned integer that can be stored is 62 bits, I am using a `bigint` to represent the decoded varint.

##### DATA Payload
In the case where the message is of type `DATA`, the payload is arbitrary data written through the sender's `WritableStream`.

##### ACK Payload

In the case where the message is of type `ACK`, the payload represents the remaining empty buffer space of the receiver. This is the `desiredSize`. This is represented as a 32bit big-endian integer (4 bytes).

##### ERROR and CLOSE Payload

In the case where the message is of type `ERROR` or `CLOSE`. The initial byte will represent whether the `ReadableStream` or the `WritableStream` of the receiver should be closed. This is represented by this enum:

```ts
enum StreamShutdown {
  Read = 0,
  Write = 1,
}
```

The remaining bytes in an `ERROR` frame should be a Var-Int with QUIC-Style `Variable-Length Integer Encoding` to represent an error code. This error code should be converted by the user of the library into a useful error by passing in a function into the constructor of `WebSocketStream`.

![image](https://github.com/MatrixAI/js-ws/assets/50583248/7e2213a5-32a3-48ee-b972-074040bccf0d)

The handling of the payloads should be so that the closing/erroring of the sender's WritableStream should close the receiver's ReadableStream and vice versa. This will be facilitated by the properties on the connection  `readableEnded` and `writableEnded`. For example, closing of a sender's writable stream should set the sender's `writableEnded` to `true`, and then send an `ERROR`/`CLOSE` message with `StreamShutdown.Read` to the receiver. The receiver will then handle the message by erroring on the `ReadableStream`'s controller, and setting `readableEnded` to `true`.

All application level errors produced by the user of the API will be converted by injected `codeToReason` and `reasonToCode` functions.

##### Error Codes

These are the following non-application errors:

```ts
const enum StreamErrorCode {
  Unknown = 0,
  // an error parsing the structure of the message
  ErrorReadableStreamParse = 1,
  // an error occurring from the buffer of a readablestream going over the maximum size
  ErrorReadableStreamBufferOverflow = 2,
}
```

All non-application errors will not be handled by the injected `codeToReason` and `reasonToCode` functions.

#### Started States

Upon starting a WebSocketStream, either:
- The WritableStream is blocked.
- The WritableStream is immediately ready.
- The WritableStream is unblocked.

![image](https://github.com/MatrixAI/js-ws/assets/50583248/984790ec-95b4-457e-a6ea-b222428c8e48)

A peer-created WebSocketStream can only be created upon receiving an Ack message. This avoids race conditions where data is sent immediately after an Ack message, causing the receiver to have a half-open WebSocketStream. This also avoids a sender creating a stream and sending Data to it without knowing what the buffer size of the receiver is.

##### Closing States

Upon closing a WritableStream, the WebSocketStream will pass by the following states:

- WritableStream Open - Peer ReadableStream Open
- WritableStream Closed - Peer ReadableStream Open (Half Closed)
- WritableStream Closed - Peer Readable Stream Closed

This opposite is true for closing a ReadableStream.

It is important to ensure that any operations that involve a blocking promise check if a Stream is closed before and after the promise resolution. This will make sure that the operations that the promises were blocking will not continue if the Stream is closed.

#### Backpressure

Backpressure will be achieved by implementing a message type that represents the acknowledgement of a message received. 

On initiation of the stream, the receiver will send an `ACK` with their buffer size to tell how much data the sender can send before blocking.

Hence, a sender will send their `DATA` and the receiver will send `ACK` when they have processed the data that the sender has sent.

The `ACK` message will be resent accordingly as data is processed by the receiver.

![image](https://github.com/MatrixAI/js-ws/assets/50583248/8341e2b2-b5b4-4808-9916-baa2a2ae6b5e)

After the first initial `ACK` sent by the receiver, the sender sets a byte counter to the value of the size of the receiver's buffer. Each subsequent `ACK` should include the `readBytes` rather than the buffer size, so that the sender can add to the counter, representing how many free bytes are available on the receiver's buffer. The sender should block when the counter reaches 0. 

If the sender were to send a message bigger than the receiver's buffer, the message should be sent in chunks. The sending of subsequent chunks after the first should be blocked on awaiting an ACK from the recipient.

!![image](https://github.com/MatrixAI/js-ws/assets/50583248/09c617b0-d285-4abe-ab0f-c4e71989cda9)

### Additional context

* Chat GPT discussion https://chat.openai.com/share/18a9bec1-adf4-425f-baf1-5645a47c24c3

### Tasks

1. [x] Spec this out.
2. [x] Implement parsing messages and message types
3. [x] Implement backpressure
4. [x] Implement error handling

**Comment by amydevs** [comment]
An extra control message needs to be introduced, being ACK.
This will allow for per-stream backpressure.
The receiver for the WS stream will have a set buffer size, where upon being reached, will be read and processed, and have an ACK message be sent back to the sender.
The sender only needs to keep a rolling counter for sent messages, which is reset after every receive of ACK.

**Comment by CMCDragonkai** [comment]
Follow this: https://chat.openai.com/share/18a9bec1-adf4-425f-baf1-5645a47c24c3 as well for the conversation regarding ACK.

**Comment by CMCDragonkai** [comment]
The backpressure mechanism along with the muxing and demuxing of streams are all tightly interconnected. So it has to be designed bit by bit. You'll need to start with just the message protocol first by using a binary header as per the first chatgpt link in https://chat.openai.com/share/18a9bec1-adf4-425f-baf1-5645a47c24c3.

Also @amydevs can you please spec out the tasks above, just think high level tasks first.

**Comment by tegefaulkes** [comment]
Good work on the spec so far, there is a good amount of information on how the back-pressure and writing works.

Small note about the ack message, As you described above I get the impression you're sending the available buffer each time you ack. Remember that this is a concurrent system. If you for example sent 500 bytes and 500 bytes quickly. When the receiving side processed the first 500 bytes and acked the 1024 available space. The sender could immediately send another 1024 bytes. At this point we'd have 1524 bytes in flight, well exceeding the available buffer. Very likely resulting in an error.

I think we should only ack the number of bytes processed and not the number of bytes available. On the sending side we keep a count of available bytes we can send. We subtract after writing and add after receiving the acks. Addition and subtraction here is commutative and atomic so we can't butcher the value. Overwriting this value concurrently will run into consistency problems.

The spec is also light on details for how the error and close messages will work. But also needs more details on how the messages are structured as well. How does an error message look? What details are included in it? Will it have an code and message? Same for the close message.

If we consider each stream as a separate state machine, how do the state transitions work? The sending and receiving streams function independently right, how does that work?

We don't need to go into full implementation detail, but we do need enough of it described so that anyone coming to this cold can understand enough of the structure to start working on it.
