### ISSUE TITLE
WebSocket Behaviour Alignment with Transport Layer

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/js-ws#3]
### Specification

This issue is an epic for tracking the pending work for the `Websockets` code.

Specifically an extraction of the behaviour to `js-ws` which behave similarly to `js-quic`.

### Additional context

* Related MatrixAI/Polykey#511
* Related MatrixAI/js-ws#4 
* Related MatrixAI/Polykey#540 
* Related MatrixAI/Polykey#400
 
### Tasks

- [x] 1. Test the backpressure from both client and server
- [x] 2. Ensure `WebSocketStream` exists and we can mux and demux on top of a single `WebSocketConnection`
- [x] 3. Make `WebSocketConection` equivalent to `QUICConnection`, but as a 1 to 1 to `WebSocket`

**Comment by CMCDragonkai** [comment]
@amydevs please have this and #4 fixed by #5, and please comment here on how this was solved based on today's discussion.

**Comment by amydevs** [comment]
The backpressure has been revised, speced, and implemented in #5. Instead of calling `.pause` on `ws.WebSocket`, we are doing backpressure per stream, and forgoing backpressure on the entire connection. The reason for this is 'pausing' the entire `WebSocketConnection` will unnecessary throttle all `WebSocketStream`s where backpressure should only need to be applied per-stream.
